
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from PIL import Image
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label
from customtkinter import *

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\ilyxa_paint\paint\build2\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#202020")


canvas = Canvas(
    window,
    bg = "#202020",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

bar = PhotoImage(file=relative_to_assets("da.png"))
label = Label(window, background="#202020", image=bar)
label.pack()
label.place(
    x=225,
    y=999,
)

ely_logo_im = PhotoImage(
    file=relative_to_assets("4.png"))
ely_logo_btn = Button(
    image=ely_logo_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
ely_logo_btn.place(
    x=955.0,
    y=1005.0,
    width=50.0,
    height=50.0
)
    # 225.0, x
    # 950.0, высота (y)
    # 1685.0, x
    # 999.0, высота (y)

eraser_im = PhotoImage(
    file=relative_to_assets("3.png"))
eraser_btn = Button(
    image=eraser_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
eraser_btn.place(
    x=805.0,
    y=1005.0,
    width=50.0,
    height=50.0
)

pencil_im = PhotoImage(
    file=relative_to_assets("2.png"))
pencil_btn = Button(
    image=pencil_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
pencil_btn.place(
    x=655.0,
    y=1005.0,
    width=50.0,
    height=50.0
)

brush_im = PhotoImage(
    file=relative_to_assets("1.png"))
brush_btn = Button(
    image=brush_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
brush_btn.place(
    x=505.0,
    y=1005.0,
    width=50.0,
    height=50.0
)

txt_im = PhotoImage(
    file=relative_to_assets("5.png"))
txt_btn = Button(
    image=txt_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
txt_btn.place(
    x=1105.0,
    y=1005.0,
    width=50.0,
    height=50.0
)

shapes_im = PhotoImage(
    file=relative_to_assets("6.png"))
shapes_btn = Button(
    image=shapes_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
shapes_btn.place(
    x=1255.0,
    y=1005.0,
    width=50.0,
    height=50.0
)

filling_im = PhotoImage(
    file=relative_to_assets("7.png"))
filling_btn = Button(
    image=filling_im,
    borderwidth=0,
    highlightthickness=0,
    bg = "#D9D9D9",
    activebackground="#D9D9D9",
    relief="flat",
)
filling_btn.place(
    x=1405.0,
    y=1005.0,
    width=50.0,
    height=50.0
)

window.resizable(False, False)
window.mainloop()
